name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name:
        run: |
         npm install
         npm run build
        
     